stage_list: ['trial']

genome_file: "GRCh38_ref.fa"

genome_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/GRCh38.primary_assembly.genome.fa.gz"

resources:
    default:
        threads: 1
        mem_mb: 4000
        runtime: 1
        partition: short
    visor_hack:
        threads: 24
        mem_mb: 16000
        runtime: 5   
        partition: short
    generate_bed:
        threads: 1
        mem_mb: 1000
        runtime: 1
        partition: short
    visor_laser:
        threads: 52
        mem_mb: 364000
        runtime: 5760  
        partition: long
    sniffles:
        threads: 8
        mem_mb: 4000
        runtime: 20  
        partition: short
    severus:
        threads: 24
        mem_mb: 40000
        runtime: 120  
        partition: short
    svision:
        threads: 52
        mem_mb: 40000
        runtime: 120  
        partition: gpu
        slurm_extra: "--gres=gpu:A100:1"
        model: /home/fvillena/SVision-pro/src/pre_process/model_liteunet_1024_8_16_32_32_32.pth
params:       
    coverage: 30
    read_type: nanopore