# Here you can specify the name of one or more directories with the stages you want to simulate:
stage_list: ['trial']

genome_file: "GRCh38_ref.fa"
genome_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/GRCh38.primary_assembly.genome.fa.gz"