stage_list: ['trial']

genome_file: "GRCh38_ref.fa"

genome_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/GRCh38.primary_assembly.genome.fa.gz"

resources:
    default:
        threads: 1
        mem_mb: 4000
        runtime: 30
    visor_hack:
        threads: 24
        mem_mb: 16000
        runtime: 120   
    generate_bed:
        threads: 1
        mem_mb: 1000
        runtime: 30
    visor_laser:
        threads: 48
        mem_mb: 64000
        runtime: 21600  
        
params:       
    coverage: 1
    read_type: nanopore